# Generated by Django 5.2.16 on 2026-07-18 18:42

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        ('encounters', '0001_initial'),
        ('test_catalogue', '0001_initial'),
        ('requests', '0001_initial'),
        ('samples', '0001_initial'),
        ('results', '0001_initial'),
        ('billing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('equipment', '0001_initial'),
        ('referrals', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_patient_statistics AS
            SELECT 
                gender,
                COUNT(id) AS patient_count,
                YEAR(created_at) AS registration_year,
                MONTH(created_at) AS registration_month
            FROM patients_patient
            WHERE is_deleted = 0
            GROUP BY gender, YEAR(created_at), MONTH(created_at);
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_patient_statistics;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_daily_revenue AS
            SELECT 
                DATE(payment_date) AS payment_date,
                payment_method,
                SUM(amount_paid) AS total_revenue
            FROM billing_payment
            WHERE is_deleted = 0
            GROUP BY DATE(payment_date), payment_method;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_daily_revenue;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_test_volume AS
            SELECT 
                t.code AS test_code,
                t.name AS test_name,
                tc.name AS category_name,
                COUNT(rt.id) AS order_count
            FROM requests_requestedtest rt
            JOIN test_catalogue_test t ON rt.test_id = t.id
            JOIN test_catalogue_testcategory tc ON t.category_id = tc.id
            WHERE rt.is_deleted = 0
            GROUP BY t.code, t.name, tc.name;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_test_volume;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_sample_tracking AS
            SELECT 
                s.barcode_number,
                s.sample_type,
                s.status,
                s.collected_at,
                s.received_at,
                u.username AS collected_by_user
            FROM samples_sample s
            LEFT JOIN accounts_user u ON s.collected_by_id = u.id
            WHERE s.is_deleted = 0;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_sample_tracking;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_turnaround_time AS
            SELECT 
                tr.request_number,
                p.first_name,
                p.last_name,
                t.name AS test_name,
                rt.status AS test_status,
                tr.request_date,
                s.collected_at,
                s.received_at,
                r.recorded_at,
                r.verified_at,
                TIMESTAMPDIFF(MINUTE, tr.request_date, r.verified_at) AS total_tat_minutes,
                TIMESTAMPDIFF(MINUTE, s.collected_at, s.received_at) AS transport_time_minutes,
                TIMESTAMPDIFF(MINUTE, s.received_at, r.recorded_at) AS processing_time_minutes,
                TIMESTAMPDIFF(MINUTE, r.recorded_at, r.verified_at) AS verification_time_minutes
            FROM requests_requestedtest rt
            JOIN requests_testrequest tr ON rt.request_id = tr.id
            JOIN encounters_encounter e ON tr.encounter_id = e.id
            JOIN patients_patient p ON e.patient_id = p.id
            JOIN test_catalogue_test t ON rt.test_id = t.id
            LEFT JOIN samples_sample s ON s.request_id = tr.id AND LOWER(s.sample_type) = LOWER(t.sample_type)
            LEFT JOIN results_result r ON r.requested_test_id = rt.id
            WHERE rt.is_deleted = 0;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_turnaround_time;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_staff_productivity AS
            SELECT 
                u.username,
                u.role,
                COUNT(r.id) AS results_entered_count
            FROM accounts_user u
            LEFT JOIN results_result r ON r.recorded_by_id = u.id
            GROUP BY u.username, u.role;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_staff_productivity;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_inventory_status AS
            SELECT 
                r.name AS reagent_name,
                r.code AS reagent_code,
                r.current_quantity,
                r.min_stock_level,
                r.expiry_date,
                CASE 
                    WHEN r.current_quantity <= r.min_stock_level THEN 'low_stock'
                    WHEN r.expiry_date <= CURRENT_DATE() THEN 'expired'
                    ELSE 'adequate'
                END AS alert_status
            FROM inventory_reagent r
            WHERE r.is_deleted = 0;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_inventory_status;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_equipment_utilization AS
            SELECT 
                eq.name AS equipment_name,
                eq.serial_number,
                eq.status AS current_status,
                COUNT(ml.id) AS maintenance_count,
                SUM(ml.cost) AS total_maintenance_cost
            FROM equipment_equipment eq
            LEFT JOIN equipment_maintenancelog ml ON ml.equipment_id = eq.id
            WHERE eq.is_deleted = 0
            GROUP BY eq.name, eq.serial_number, eq.status;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_equipment_utilization;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_quality_metrics AS
            SELECT 
                qc.name AS control_name,
                qc.lot_number,
                COUNT(run.id) AS total_runs,
                SUM(CASE WHEN run.status = 'pass' THEN 1 ELSE 0 END) AS passed_runs,
                SUM(CASE WHEN run.status = 'fail' THEN 1 ELSE 0 END) AS failed_runs,
                CASE 
                    WHEN COUNT(run.id) > 0 THEN (SUM(CASE WHEN run.status = 'pass' THEN 1 ELSE 0 END) / COUNT(run.id)) * 100
                    ELSE 0.00
                END AS pass_rate_percent
            FROM quality_qccontrol qc
            LEFT JOIN quality_qcrun run ON run.control_id = qc.id
            WHERE qc.is_deleted = 0
            GROUP BY qc.name, qc.lot_number;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_quality_metrics;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW vw_referral_statistics AS
            SELECT 
                partner.name AS partner_name,
                ref.referral_type,
                ref.status,
                COUNT(ref.id) AS referral_count
            FROM referrals_referral ref
            JOIN referrals_referralpartner partner ON ref.partner_id = partner.id
            WHERE ref.is_deleted = 0
            GROUP BY partner.name, ref.referral_type, ref.status;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_referral_statistics;"
        ),
    ]
