# Generated by Django 5.2.16 on 2026-07-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('laboratory_manager', 'Laboratory Manager'), ('pathologist', 'Pathologist'), ('laboratory_scientist', 'Laboratory Scientist'), ('laboratory_technician', 'Laboratory Technician'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('store_officer', 'Store Officer'), ('quality_officer', 'Quality Officer'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='receptionist', max_length=30),
        ),
    ]
