# Generated by Django 5.2.16 on 2026-07-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccontrol',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
